CREATE TABLE `googleplay` (
  `id` int(15) NOT NULL AUTO_INCREMENT,
  `url` varchar(250) CHARACTER SET utf8 NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 NOT NULL,
  `name` varchar(100) CHARACTER SET utf8 NOT NULL,
  `devid` varchar(100) CHARACTER SET utf8 NOT NULL,
  `icon` varchar(150) CHARACTER SET utf8 NOT NULL,
  `images` varchar(2000) CHARACTER SET utf8 NOT NULL,
  `category` varchar(50) CHARACTER SET utf8 NOT NULL,
  `whatsnew` varchar(300) CHARACTER SET utf8 NOT NULL,
  `datepublished` varchar(20) CHARACTER SET utf8 NOT NULL,
  `filesize` varchar(20) CHARACTER SET utf8 NOT NULL,
  `numdownload` varchar(30) CHARACTER SET utf8 NOT NULL, 
  `version` varchar(20) CHARACTER SET utf8 NOT NULL,
  `requirementsos` varchar(20) CHARACTER SET utf8 NOT NULL,
  `devemail` varchar(50) CHARACTER SET utf8 NOT NULL,
  `devweb` varchar(250) CHARACTER SET utf8 NOT NULL,
  `score` varchar(5) CHARACTER SET utf8 NOT NULL,
  `content_rating` varchar(50) CHARACTER SET utf8 NOT NULL,
  `star1num` int(10) NOT NULL,
  `star2num` int(10) NOT NULL,
  `star3num` int(10) NOT NULL,
  `star4num` int(10) NOT NULL,
  `star5num` int(10) NOT NULL,
  `reviewsnum` int(10) NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
